### ISSUE TITLE
После запуска SUT на порту 7777 при вводе валидных логина и пароля в регистрационную форму пишет Ошибку логина или пароля

### ISSUE THREAD

**Issue by IvanVorobev** [IvanVorobev/TestMode#1]
**Шаги по воспроизведению:**

1. Создать проект [Ссылка](https://github.com/IvanVorobev/TestMode)
2. В терминале IDEA запустить SUT командой:
`C:\IdeaProjects\TestMode\artifacts> запустить SUT командой java -jar app-ibank.jar -port=7777`
3. Для активации тестового режима при запуске SUT в терминале ввести команду:
` java -jar app-ibank.jar -P:profile=test`
4. Перейти по [Ссылка]( http://localhost:7777/) и ввести:
```
    "login": "vasya",
    "password": "password",
```
5. Нажать Продолжить.

**Ожидаемый результат:**
Успешный вход/регистрация

**Фактический результат:**
Ошибка при входе (неправильно указан логин или пароль).

**Программное окружение:**

Windows 10
IntelliJ IDEA COMMUNITY 2020.1
openjdk version "11.0.7" 2020-04-14

Скриншоты:
![AQA_ Регистрация - Google Chrome 2020-07-28 13 55](https://user-images.githubusercontent.com/63260533/88657269-55411d00-d0da-11ea-955d-a020af088b78.jpg)

**Comment by andrew-pahomov** [comment]
Вы пытаетесь запустить

**Comment by IvanVorobev** [comment]
Запустил в терминале указанную Вами команду, через минуту зашел на сайт регистрации http://localhost:7777/, ввел 
```
    "login": "vasya",
    "password": "password"
```
но ошибка сохранилась.

**Лог:**
```
Microsoft Windows [Version 10.0.18363.778]
(c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.

C:\IdeaProjects\TestMode>java -jar ./artifacts/app-ibank.jar -P:profile=test -port=7777
2020-07-28 23:36:33.667 [main] TRACE Application - {
    # application.conf @ jar:file:/C:/IdeaProjects/TestMode/artifacts/app-ibank.jar!/application.conf: 6
    "application" : {
        # application.conf @ jar:file:/C:/IdeaProjects/TestMode/artifacts/app-ibank.jar!/application.conf: 7
        "modules" : [
            # application.conf @ jar:file:/C:/IdeaProjects/TestMode/artifacts/app-ibank.jar!/application.conf: 7
            "ru.netology.aqa.ApplicationKt.module"
        ]
    },
    # application.conf @ jar:file:/C:/IdeaProjects/TestMode/artifacts/app-ibank.jar!/application.conf: 2
    "deployment" : {
        # application.conf @ jar:file:/C:/IdeaProjects/TestMode/artifacts/app-ibank.jar!/application.conf: 3
        "port" : 9999
    },
    # Content hidden
    "security" : "***"
}

2020-07-28 23:36:33.768 [DefaultDispatcher-worker-1] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
2020-07-28 23:36:34.201 [DefaultDispatcher-worker-1] INFO  Application - Responding at http://0.0.0.0:7777

2020-07-28 23:37:26.133 [DefaultDispatcher-worker-1] ERROR Application - 400 Bad Request: POST - /api/auth
ru.netology.aqa.exception.AuthInvalidException: null
        at ru.netology.aqa.service.UserService.auth(UserService.kt:29)
        at ru.netology.aqa.route.Main$setup$$inlined$with$lambda$1$2.invokeSuspend(Main.kt:43)
        at ru.netology.aqa.route.Main$setup$$inlined$with$lambda$1$2.invoke(Main.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
        at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:106)
        at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
        at io.ktor.features.StatusPages$interceptCall$2.invokeSuspend(StatusPages.kt:98)
        at io.ktor.features.StatusPages$interceptCall$2.invoke(StatusPages.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:180)
        at io.ktor.features.StatusPages.interceptCall(StatusPages.kt:97)
        at io.ktor.features.StatusPages$Feature$install$2.invokeSuspend(StatusPages.kt:137)
        at io.ktor.features.StatusPages$Feature$install$2.invoke(StatusPages.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$1$1.invokeSuspend(CIOApplicationEngine.kt:161)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by andrew-pahomov** [comment]
SUT Вы запустили, это отлично. Для выполнения входа через Web интерфейс необходимо создать клиента банка через API.     
Для создания клиента нужно делать запрос вида:

```
POST /api/system/users
Content-Type: application/json

{
    "login": "vasya",
    "password": "password",
    "status": "active" 
}
```      
Запрос Вы можете выполнить вручную в Postman. А в автотестах следует использовать REST-assured. В условии к домашнему заданию даны подсказки для формирования кода Вашего проекта.
